### ISSUE TITLE
Extra events returned incorrectly

### ISSUE THREAD

**Issue by BonsaiCode** [DHTMLX/scheduler-helper-php#12]
I created one event that repeats for two days, so I only have 2 days on the calendar.  I then use getData() to retrieve a 5 day range that includes the 2 events.  getData returns 5 events in the results, one for each day instead of just the two events that exist.

**Comment by AlexKlimenkov** [comment]
Fixed in v1.1.0
https://github.com/DHTMLX/scheduler-helper-php/releases/tag/1.1.0
