### ISSUE TITLE
Weekly Reccuring events problems in february

### ISSUE THREAD

**Issue by MrSef217** [DHTMLX/scheduler-helper-php#15]
Hello ,
We have issues with  Weekly recurring events.
please check the attached images.

![bug reccuring weekly - month equal febr 2](https://cloud.githubusercontent.com/assets/10829594/13566526/4db82ec2-e456-11e5-9fdf-1bf9485d7ea7.png)

![bug reccuring weekly - month notequal febr 2](https://cloud.githubusercontent.com/assets/10829594/13566537/5a45d32e-e456-11e5-8ba0-6892ab3007b2.png)

Thank You.

**Comment by AlexKlimenkov** [comment]
Hi,
please try version from this branch https://github.com/DHTMLX/scheduler-helper-php/tree/weekly_and_endless_series_fix
Does the issue still happen there?

**Comment by MrSef217** [comment]
Hi ,
Sadly this version didn't fix the problem.
Thank you.

**Comment by MrSef217** [comment]
Hello Alex Klimenkov, 
can you confirm if it's a bug or we are doing something wrong ?
Thank you.

**Comment by AlexKlimenkov** [comment]
Hello,
yes, it's definitely a bug from our side.
We're currently working on fixes, most probably the update will be ready next week

**Comment by AlexKlimenkov** [comment]
Hi,
we've done some fixes, please check the latest version from this branch https://github.com/DHTMLX/scheduler-helper-php/tree/weekly_and_endless_series_fix

**Comment by MrSef217** [comment]
Hello thank you for the fixes , the weekly issues are almost gone , but there are still some issues with the monthly and yearly recurring. can you take a look at these issues.
In weekly :
->first week where the serie was created is skipped for some reason .
In monthly :
->if we choose ( repeat 1 day every x month ) doesn't work if (x > 1). 
->if we choose ( on x day every x month ) doesn't work.
In yearly :
->if we choose ( on x day every x month ) doesn't work.

![recurring helper](https://cloud.githubusercontent.com/assets/10829594/13960798/169ad4fc-f05a-11e5-8594-983179dcde7f.png)

Best Regards.

**Comment by AlexKlimenkov** [comment]
Thanks, we'll check these issues and I'll give an update when we have something new (probably in the nearest couple of days)

**Comment by AlexKlimenkov** [comment]
Hi,
please check the latest version from the fix branch https://github.com/DHTMLX/scheduler-helper-php/tree/weekly_and_endless_series_fix

**Comment by MrSef217** [comment]
Hello Alex, 
Thank you for your support and your hard work .
The last update solved all the weekly issues , what's left is the monthly and yearly. please check the image.
![remaining issues](https://cloud.githubusercontent.com/assets/10829594/14042705/cd55d33a-f27c-11e5-938b-32420fdb990d.png)

Best Regards.

**Comment by AlexKlimenkov** [comment]
All issues seems to be resolved in the fix branch, we're going to update master tomorrow

**Comment by AlexKlimenkov** [comment]
Fixed in v1.1.0
https://github.com/DHTMLX/scheduler-helper-php/releases/tag/1.1.0

**Comment by MrSef217** [comment]
Thank you for the big help. 
all the issues are gone .
thanks .
