### ISSUE TITLE
getData() returns only events from the same DST 

### ISSUE THREAD

**Issue by EndOfSource** [DHTMLX/scheduler-helper-php#2]
Let's assume we have a database and a table called `events`:

This events table has the following columns:
`event_id, start_date, end_date, rec_type, event_pid, event_length.`

Add two rows to this table:

| event_id | start_date | end_date | rec_type | event_pid | event_length |
| --- | --- | --- | --- | --- | --- |
| 21 | 2014-09-08 00:00:00 | 9999-02-01 00:00:00 | week_1___1,2,3,4,5#no | 0 | 86400 |
| 43 | 2015-07-16 00:00:00 | 2015-07-17 00:00:00 |  | 0 | 0 |

Initialize a scheduler-helper instance:

``` php
$helper = new Helper(
            array(
                "dbsm" => "mysql", 
                "host" => "localhost",
                "db_name" => "dbname",
                "user" => "someuser",
                "password" => "supersecurepassword",
                "table_name" => "events"
            )
        );
```

Request all events with `start_date` `'2015-07-16 00:00:00'` and `end_date` `'2015-07-17 00:00:00'` 

``` php
$events = $helper->getData('2015-07-15 23:59:59', '2015-07-17 00:00:00');
```

Result:

``` php
array(1) {
  [0]=>
  array(12) {
    ["event_id"]=>
    string(2) "43"
    ["start_date"]=>
    string(19) "2015-07-16 00:00:00"
    ["end_date"]=>
    string(19) "2015-07-17 00:00:00"
    ["rec_type"]=>
    string(0) ""
    ["event_pid"]=>
    string(1) "0"
    ["event_length"]=>
    string(1) "0"
  }
}
```

The event that starts in September 2014 with id `21` is not displayed.

**Comment by ABDows** [comment]
yes , I get the same problem ! I tried to fixe it but @?#&, Someone found a solution ?

**Comment by EndOfSource** [comment]
They already fixed it for me because I have a "Support Membership" on their site as well. I just aksed them if they could upload the changes to GitHub as well. It should be fixed in the next couple of days for everyone!

**Comment by MrSef217** [comment]
same problem , please how to fix it !!

**Comment by ABDows** [comment]
can you just drop message if the fix is uploaded plz ?

**Comment by EgorLazarovich** [comment]
Hello. This problem should be fixed in this commit https://github.com/DHTMLX/scheduler-helper-php/commit/601518cbcf4cbdf9429993e280a44e5e8b905721. Please, check this in your project.

**Comment by sanadiab** [comment]
yes , I get the same problem ! I tried to fixe it but @?#&, Someone found a solution ?
