### ISSUE TITLE
Helper Bug (July)

### ISSUE THREAD

**Issue by MrSef217** [DHTMLX/scheduler-helper-php#26]
Hello  ,
i have an issue with scheduler Helper , i created a reccuring event for each first monday in the month , the weird thing is if the search interval is less than 20 days (2016-07-01) the helper returns empty data when it should return something.

$db_host = ""   ;
$db_name = "" ;
$db_username = "";
$db_pwd = "

" ;

$helper = new Helper(
array(
      "dbsm" => "mysql",
      "host" => $db_host,
      "db_name" => $db_name,
      "user" => $db_username,
      "password" => $db_pwd,
      "table_name" => "time_slots"  )
);

$helper->setFieldsNames(array(
   helper::FLD_ID => "time_slot_id",
));

// working !!!!
$start_date_str = '2016-06-30 08:00:00'; 
$end_date_str = '2016-07-05 23:59:59';

// not working
$start_date_str = '2016-07-01 08:00:00'; 
$end_date_str = '2016-07-05 23:59:59'; 

// not working
$start_date_str = '2016-07-01 08:00:00'; 
$end_date_str = '2016-07-21 23:59:59'; 

// not working : interval lt 20 days
$start_date_str = '2016-07-05 08:00:00'; 
$end_date_str = '2016-07-24 23:59:59';

// working
$start_date_str = '2016-07-04 08:00:00'; 
$end_date_str = '2016-07-24 23:59:59';

// working : interval gt 20 days
$start_date_str = '2016-07-02 08:00:00'; 
$end_date_str = '2016-07-22 23:59:59'; 

$all_event = $helper->getData($start_date_str, $end_date_str);
var_dump($all_event);

![time slot](https://cloud.githubusercontent.com/assets/10829594/16562238/bf15f014-41fc-11e6-8a7c-9294f6e4a645.png)

please check the attached files for more information.

**Comment by AlexKlimenkov** [comment]
Hi,
confirmed. Please try the latest version from a master branch https://github.com/DHTMLX/scheduler-helper-php
The issue should be fixed now
