### ISSUE TITLE
Problem when "count" is "NaN" for the rec_type field

### ISSUE THREAD

**Issue by EndOfSource** [DHTMLX/scheduler-helper-php#28]
For an currently unknown reason we have database entries with `rec_type = week_NaN___1,2,3,4#` (just an example).
The consistent part for those broken is that `count` is always `NaN`.

I tried to figrue out the best way to fix this but somewhat lost.

Here is one row that causes the error:

| start_date | end_date | rec_type | event_pid | event_length |
| --- | --- | --- | --- | --- |
| 2016-06-29 00:00:00 | 9999-02-01 00:00:00 | week_NaN___1,2,3,4# | 0 | 86400 |

Thanks for your help in advance!

**Comment by AlexKlimenkov** [comment]
Hello,
I'm not sure whether it's the best solution (meaning the pull request https://github.com/DHTMLX/scheduler-helper-php/pull/29 ), at least while php-helper does not have any error logging. 
NaN values come from the client side, that may mean that there is something wrong with the recurring control of the lightbox ('rec_type' is generated there).
Skipping such records on a backend will hide this issue until it pops up somewhere else.

rec_type string is generated in this method of dhtmlxscheduler_recurring.js
https://github.com/DHTMLX/scheduler/blob/v4.3.1/codebase/sources/ext/dhtmlxscheduler_recurring.js#L152

and week recurring from your example is created here
https://github.com/DHTMLX/scheduler/blob/v4.3.1/codebase/sources/ext/dhtmlxscheduler_recurring.js#L268

Here is the line which gets NaN:
`code.push(Math.max(1, get_value(els, "week_count")));`

'get_value' does not guarantee to return a numeric value, probably that's the case - when it return undefined value (form does not have 'week_count' control), you'll get NaN in rec_type string -

```
Math.max(1, undefined);
--> NaN
```

There should be checking like following
`code.push(Math.max(1, (get_value(els, "week_count") * 1) || 0));`

There are several other places where such checking might be useful
https://github.com/DHTMLX/scheduler/blob/v4.3.1/codebase/sources/ext/dhtmlxscheduler_recurring.js#L303 
https://github.com/DHTMLX/scheduler/blob/v4.3.1/codebase/sources/ext/dhtmlxscheduler_recurring.js#L253
https://github.com/DHTMLX/scheduler/blob/v4.3.1/codebase/sources/ext/dhtmlxscheduler_recurring.js#L256

We'll make a correction to a dev version of dhtmlxScheduler. If you can open a ticket in our support system we'll provide you the latest of the scheduler. Or you can patch dhtmlxscheduler_recurring.js locally, the next version of the component will contain a fix

**Comment by EndOfSource** [comment]
Hello @AlexKlimenkov! 
Thanks for the fast reply!

My ticket id is "XJK-721971". 

I'm closing my pull request #29 now because this solution is only temporary (like you said).
