### ISSUE TITLE
getData ignores recurring long events

### ISSUE THREAD

**Issue by MrSef217** [DHTMLX/scheduler-helper-php#30]
Hello , 

Why is getData doesn't return any event  where recurring event is +24 hours ? is this a bug ?

![image](https://cloud.githubusercontent.com/assets/10829594/17628413/7d7ecf72-60b5-11e6-9a80-e836fcd18d81.png)
![image](https://cloud.githubusercontent.com/assets/10829594/17628436/9dcb9b70-60b5-11e6-9c39-d8467b611f9a.png)

start date : "2016-08-12 17:55:00"
end date   : "2016-08-15 23:59:59"
result :

array:1 [
  0 => array:13 [
    "event_id" => "p106"
    "start_date" => "2016-08-09 11:20:00"
    "end_date" => "2016-08-13 10:40:00"
    "blocked" => "1"
    "event_type" => "p"
    "prestation_id" => null
    "agenda_id" => "56"
    "rec_type" => ""
    "event_pid" => "p0"
    "event_length" => "0"
    "online" => "0"
    "start_time" => 1470741600
    "end_time" => 1471084800
  ]
]

Thanks .

**Comment by MrSef217** [comment]
Hello ,
can you confirm if it's a bug , does the helper support recurring long events  ?
Thank you.

**Comment by MrSef217** [comment]
can you please confirm this issue ?

**Comment by AlexKlimenkov** [comment]
Hi,
sorry for a delay.
The bug should be fixed now #31

**Comment by MrSef217** [comment]
great , thank you very much .
