### ISSUE TITLE
UTC & day of week bugfix

### ISSUE THREAD

**Issue by BonsaiCode** [DHTMLX/scheduler-helper-php#34]
Bug description:

Recurring event with start of 2017-11-16 00:00:00 UTC (Thurs) which is 2017-11-15 17:00:00 EST (Wed).

SchedulerHelperDate.getDayOfWeek returns a 4 for Thurs, but should return a 3 for localtime Wed to retrieve correct events.

(All scheduler start and finish values in my database are stored in UTC)

Solution: update SchedulerHelperDate.getDayOfWeek() to return local date of week for the given UTC timestamp:

old code:

    static public function getDayOfWeek($timestamp) {
        $weekDay = getdate($timestamp)["wday"];
        return $weekDay;
    }

new code:

    static public function getDayOfWeek($timestamp) {
        # We need to get the day of week in local time
        # e.g. UTC time: 2017-11-16 00:00:00 (Thurs) is 2017-11-15 5pm EST (Wed)
        # old way would return 4 (Thurs), but we need local time 3 (Wed)

        # In order to convert to another named timezone, we MUST instantiate the following way in order for $datetime['timezone_type'] to be 3 (named timezone)
        # see https://stackoverflow.com/questions/17694894/different-timezone-types-on-datetime-object
        # this will not convert timezone correctly: $datetime = new \DateTime( '@'.$dateStamp );

        $datetime = new \DateTime( date( 'Y-m-d H:i:s', $timestamp ), new \DateTimeZone( 'UTC' ) );

        # TODO: Update this method, getDayOfWeek, to accept a target timezone parameter instead of hardcoding here
        $datetime->setTimezone( new \DateTimeZone( 'America/New_York' ) );
        $weekDay = $datetime->format( 'w' );
        return $weekDay;
    }

the alternative is to leave the original code as is and call php's `date_default_timezone_set()` to set the desired timezone before using any date/time related code.

**Comment by ArtiBorisevich** [comment]
Hello,
As I understand, you want to convert your data from UTC to the actual client timezone and load it in the Scheduler. There is a suitable configuration property `server_utc` with this enabled option, each time when data need to be saved in DB, it will be converted from local time to UTC ( so DB will hold UTC time ), and during loading, data will be converted from UTC to actual client timezone, so clients in different timezones will see the different time of the same event. Please check this article: 
https://docs.dhtmlx.com/scheduler/api__scheduler_server_utc_config.html

**Comment by BonsaiCode** [comment]
This issue probably is no longer applicable, at least to me.  I ended up storing all times in the user's local time zone.
